//! Tauri command handlers - the IPC surface the frontend invokes.

use std::path::PathBuf;

use tauri::{AppHandle, Emitter, Manager, State};
use uuid::Uuid;

use crate::config::{AccountConfig, AppConfig};
use crate::paths;
use crate::provider::registry;
use crate::provider::registry::ProviderDescriptor;
use crate::provider::{Credentials, ProviderKind, Snapshot};
use crate::scheduler;
use crate::state::AppState;
use crate::vault::Vault;

#[tauri::command]
pub fn get_config(app: AppHandle) -> AppConfig {
    AppState::config(&app)
}

#[tauri::command]
pub fn list_providers() -> Vec<ProviderDescriptor> {
    registry::descriptors()
}

#[tauri::command]
pub async fn add_account(
    app: AppHandle,
    label: String,
    provider: String,
    credentials: Credentials,
) -> Result<AccountConfig, String> {
    let kind =
        registry::parse_kind(&provider).ok_or_else(|| format!("unknown provider: {provider}"))?;
    let id = Uuid::new_v4().to_string();

    let adapter = registry::make(kind);
    let fetch_result = adapter
        .fetch(&id, &credentials)
        .await
        .map_err(|e| e.to_string())?;
    let credentials_to_store = fetch_result
        .updated_credentials
        .clone()
        .unwrap_or(credentials);
    let account = persist_account(&app, id.clone(), label, provider, credentials_to_store)?;

    if let Some(cache) = app.try_state::<scheduler::SnapshotCache>() {
        cache
            .inner()
            .lock()
            .await
            .insert(id, fetch_result.snapshot.clone());
    }
    let _ = app.emit("usage:update", &fetch_result.snapshot);

    Ok(account)
}

/// Opens a normal Codex sign-in in an isolated profile for one account.
#[tauri::command]
pub fn start_codex_sign_in() -> Result<CodexProfileSession, String> {
    let profile_id = Uuid::new_v4().to_string();
    let profile_dir = codex_profile_dir(&profile_id)?;
    std::fs::create_dir_all(&profile_dir).map_err(|e| e.to_string())?;

    // Force file-backed credentials inside this isolated CODEX_HOME. The
    // profile remains the one source of truth for Codex, not TokenMaxxer's vault.
    std::fs::write(
        profile_dir.join("config.toml"),
        "cli_auth_credentials_store = \"file\"\n",
    )
    .map_err(|e| e.to_string())?;

    launch_codex_login(&profile_dir)?;

    Ok(CodexProfileSession { profile_id })
}

/// Registers a completed isolated Codex profile. Only a profile id generated by
/// `start_codex_sign_in` is accepted; credentials stay in that profile's
/// `auth.json` and are never copied into the TokenMaxxer vault.
#[tauri::command]
pub fn complete_codex_profile(
    app: AppHandle,
    profile_id: String,
    label: String,
) -> Result<AccountConfig, String> {
    let profile_dir = codex_profile_dir(&profile_id)?;
    let auth_path = profile_dir.join("auth.json");
    let raw = std::fs::read_to_string(&auth_path).map_err(|_| {
        "No Codex login was found for this profile. Run the shown command first.".to_string()
    })?;
    crate::provider::codex::validate_auth_json(&raw).map_err(|e| e.to_string())?;

    let account_id = Uuid::new_v4().to_string();
    let account_label = if label.trim().is_empty() {
        "Codex Account".to_string()
    } else {
        label.trim().to_string()
    };
    let credentials = serde_json::json!({
        "kind": "codex_profile",
        "profile_id": profile_id,
    });

    persist_account(
        &app,
        account_id,
        account_label,
        "codex".to_string(),
        credentials,
    )
}

#[tauri::command]
pub async fn remove_account(app: AppHandle, id: String) -> Result<(), String> {
    let mut config = AppState::config(&app);
    let account = config.accounts.iter().find(|a| a.id == id).cloned();
    let Some(account) = account else {
        return Ok(());
    };

    let profile_id = Vault::load()
        .ok()
        .and_then(|vault| vault.get(&account.auth_ref).cloned())
        .and_then(codex_profile_id_from_credentials);

    config.remove_account(&id);
    config.save().map_err(|e| e.to_string())?;

    if let Ok(mut vault) = Vault::load() {
        let _ = vault.remove(&account.auth_ref);
    }

    if account.provider == "codex" {
        if let Some(profile_id) = profile_id {
            let profile_dir = codex_profile_dir(&profile_id)?;
            if profile_dir.exists() {
                std::fs::remove_dir_all(profile_dir).map_err(|e| e.to_string())?;
            }
        }
    }

    Ok(())
}

#[tauri::command]
pub async fn refresh_account(app: AppHandle, id: String) -> Result<Snapshot, String> {
    Ok(scheduler::refresh_one(&app, &id).await)
}

#[tauri::command]
pub async fn get_snapshot(
    _app: AppHandle,
    id: String,
    cache: State<'_, scheduler::SnapshotCache>,
) -> Result<Option<Snapshot>, String> {
    Ok(cache.lock().await.get(&id).cloned())
}

#[tauri::command]
pub async fn get_history(
    app: AppHandle,
    id: String,
) -> Result<Vec<crate::scheduler::UsageEvent>, String> {
    Ok(scheduler::history_for(&app, &id).await)
}

fn persist_account(
    app: &AppHandle,
    id: String,
    label: String,
    provider: String,
    credentials: Credentials,
) -> Result<AccountConfig, String> {
    let auth_ref = format!("{provider}-{id}");
    let mut vault = Vault::load().map_err(|e| e.to_string())?;
    vault
        .put(auth_ref.clone(), credentials)
        .map_err(|e| e.to_string())?;

    let account = AccountConfig {
        id,
        label,
        provider,
        auth_ref,
    };
    let mut config = AppState::config(app);
    config.add_account(account.clone());
    config.save().map_err(|e| e.to_string())?;
    Ok(account)
}

fn codex_profile_dir(profile_id: &str) -> Result<PathBuf, String> {
    let profile_id =
        Uuid::parse_str(profile_id).map_err(|_| "invalid Codex profile identifier".to_string())?;
    paths::codex_profiles_dir()
        .map(|root| root.join(profile_id.to_string()))
        .map_err(|e| e.to_string())
}

fn codex_profile_id_from_credentials(credentials: Credentials) -> Option<String> {
    (credentials.get("kind")?.as_str()? == "codex_profile")
        .then(|| credentials.get("profile_id")?.as_str().map(str::to_owned))
        .flatten()
}

#[derive(serde::Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CodexProfileSession {
    profile_id: String,
}

#[cfg(windows)]
fn launch_codex_login(profile_dir: &std::path::Path) -> Result<(), String> {
    let script_path = profile_dir.join("codex-login.cmd");
    let script = format!(
        "@echo off\r\nset \"CODEX_HOME={}\"\r\ncodex login\r\n",
        profile_dir.display(),
    );
    std::fs::write(&script_path, script)
        .map_err(|e| format!("Could not prepare Codex sign-in: {e}"))?;

    std::process::Command::new("cmd")
        .args(["/C", "start", "TokenMaxxer Codex Sign-in", "cmd", "/K"])
        .arg(&script_path)
        .spawn()
        .map_err(|e| format!("Could not open Codex sign-in: {e}"))?;
    Ok(())
}

#[cfg(not(windows))]
fn launch_codex_login(_profile_dir: &std::path::Path) -> Result<(), String> {
    Err("Guided Codex sign-in is currently available in the Windows app.".into())
}

/// A loose enum so the serde layer round-trips the string kinds we persist.
#[allow(dead_code)]
fn _kind_doc(_k: ProviderKind) {}
